set(LIBSTM32_PLATFORM "${CMAKE_CURRENT_SOURCE_DIR}/stm32qemu")

set(LIBSTM32_QEMU_LINKER_SCRIPT "${LIBSTM32_PLATFORM}/qemu.ld")
#set(LIBSTM32_STARTUP_DEFS "-D__STARTUP_CLEAR_BSS -D__START=main -D__EXIT=mexit")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-function -mcpu=cortex-m3 -mthumb -fdata-sections -ffunction-sections -DSTM32F10X_MD_VL -DUSE_STDPERIPH_DRIVER -DQEMU_SUPPORT --specs=nano.specs --specs=rdimon.specs ${LIBSTM32_STARTUP_DEFS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_LD_FLAGS} -T${LIBSTM32_QEMU_LINKER_SCRIPT} -mthumb -mcpu=cortex-m3 -Wl,-Map,linker.map -Wl,--gc-sections -Wl,--strip-debug")

set(LIBSTM32_EXT_LIBS "${LIBSTM32_PLATFORM}/stm32-ext-libs")
set(LIBSTM32_TEMPLATE "${LIBSTM32_EXT_LIBS}/STM32-Template")

set(LIBSTM32_DEVICE "${LIBSTM32_EXT_LIBS}/stm32vldiscovery_package/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x")
set(LIBSTM32_CORE "${LIBSTM32_EXT_LIBS}/stm32vldiscovery_package/Libraries/CMSIS/CM3/CoreSupport")
set(LIBSTM32_PERIPH "${LIBSTM32_EXT_LIBS}/stm32vldiscovery_package/Libraries/STM32F10x_StdPeriph_Driver")

file(GLOB LIBSTM32_CORE_SOURCES "${LIBSTM32_CORE}/*.c")
file(GLOB LIBSTM32_DEVICE_SOURCES "${LIBSTM32_DEVICE}/*.c")
file(GLOB LIBSTM32_TEMPLATE_SOURCES "${LIBSTM32_TEMPLATE}/*.c")
file(GLOB LIBSTM32_PERIPH_SOURCES "${LIBSTM32_PERIPH}/src/*.c")
file(GLOB LIBSTM32_PLATFORM_SOURCES "${LIBSTM32_PLATFORM}/*.c")
list(REMOVE_ITEM LIBSTM32_PLATFORM_SOURCES "${LIBSTM32_PLATFORM}/exit.c")
configure_file("${LIBSTM32_PLATFORM}/exit.c" "${CMAKE_PATCHER_OUTPUT_DIRECTORY}/libstm32_platform/exit.c" COPYONLY)
list(APPEND LIBSTM32_PLATFORM_SOURCES "${CMAKE_PATCHER_OUTPUT_DIRECTORY}/libstm32_platform/exit.c")

add_library(stm32 STATIC ${LIBSTM32_CORE_SOURCES} ${LIBSTM32_DEVICE_SOURCES} ${LIBSTM32_TEMPLATE_SOURCES} ${LIBSTM32_PERIPH_SOURCES} ${LIBSTM32_PLATFORM_SOURCES})
target_include_directories(stm32 PUBLIC ${LIBSTM32_CORE} ${LIBSTM32_DEVICE} ${LIBSTM32_PLATFORM}/include ${LIBSTM32_TEMPLATE} ${LIBSTM32_TEMPLATE}/Library ${LIBSTM32_PERIPH}/inc ${LIBSTM32_PLATFORM})
